# https://taskfile.dev
version: '3'

tasks:

  setup:
    desc: Setup linter, formatter, etc. for local testing and CI
    cmds:
      - task: brew-install-go
      - task: brew-install-jq

  lint:
    desc: Formatting and linting
    cmds:
      - test -z "$(go tool gofumpt -d -e . | tee /dev/stderr)"
      - go tool golangci-lint run --timeout 5m

  fix:
    desc: Fix formatting and linting
    cmds:
      - go tool gofumpt -w .
      - go mod tidy
      - go tool golangci-lint run --timeout 5m --fix

  deps:
    desc: Update dependencies
    cmds:
      - go get -u
      - go mod tidy

  test:
    desc: Run tests
    dir: "{{.SRC_DIR}}"
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -v ./... {{ .CLI_ARGS }}
    silent: true

  ci:
    desc: Workflow to run in CI
    deps: [setup]
    cmds:
      - task: lint
      - task: test

  build:
    cmds:
      - go build . {{ .CLI_ARGS }}

  run:
    cmds:
      - go run main.go {{ .CLI_ARGS }}

  brew-install-go:
    internal: false
    platforms: [darwin]
    cmds: ["which go > /dev/null || brew install go"]
    preconditions:
      - sh: 'which brew'
        msg: '"brew" needed to install "go"- see https://brew.sh'

  brew-install-jq:
    internal: false
    platforms: [darwin]
    cmds: ["which jq > /dev/null || brew install jq"]
    preconditions:
      - sh: 'which brew'
        msg: '"brew" needed to install "jq"- see https://brew.sh'
